"""
getDHData.py
============
Data loader for DH_Cascade_Framework_v2.

Returns a flat dictionary following the same pattern as the original
ETHOS.FINE getData.py:
    key  = "ComponentName, parameterType"
    value = pandas.Series (scalar / capacity data)
          | pandas.DataFrame (time series: 8760 × 15, or matrix: 15 × 15)

All InputData files are read from InputData/ relative to this script.
Time-series DataFrames have integer index 0..8759 and county-name columns.
Matrix DataFrames have county-name index and county-name columns.
Scalar data is returned as pandas.Series with county-name index.

DATA STATUS
-----------
All data files in InputData/ were generated by generate_synthetic_data.py
and are SYNTHETIC placeholder data.  Replace files with real Estonian
measurements before any optimisation or publication.

Usage
-----
    from getDHData import getDHData
    data = getDHData()
    # e.g.
    print(data["Heat demand HTDHN, operationRateFix"].shape)   # (8760, 15)
    print(data["Biomass boiler, capacityMax"])                  # Series (15,)
"""

import pandas as pd
from pathlib import Path

_BASE = Path(__file__).parent / "InputData"
_READ = dict(index_col=0, engine="openpyxl")   # matches original getData.py pattern


def _read_ts(subfolder: str, filename: str) -> pd.DataFrame:
    """Read 8760 × 15 time-series Excel file."""
    return pd.read_excel(_BASE / subfolder / filename, sheet_name="data", **_READ)


def _read_mat(subfolder: str, filename: str) -> pd.DataFrame:
    """Read 15 × 15 matrix Excel file (county × county)."""
    return pd.read_excel(_BASE / subfolder / filename, sheet_name="data", **_READ)


def _read_scalar(subfolder: str, filename: str, col: str) -> pd.Series:
    """Read scalar Series (one value per county) from a single-column Excel file."""
    df = pd.read_excel(_BASE / subfolder / filename, sheet_name="data", **_READ)
    return df[col]


# ── Public counties list (canonical order) ────────────────────────────────────
COUNTIES = [
    "Harju", "Hiiu", "Ida-Viru", "Jogeva", "Jarva",
    "Laane", "Laane-Viru", "Polva", "Parnu", "Rapla",
    "Saare", "Tartu", "Valga", "Viljandi", "Voru",
]


def getDHData() -> dict:
    """
    Load all InputData for the DH Cascade Framework.

    Returns
    -------
    dict
        Keys: "ComponentName, parameterType"
        Values: pd.Series or pd.DataFrame

    Component names follow ETHOS.FINE naming conventions so that
    buildModel.py can pass them directly to fn.Source / fn.Conversion /
    fn.Storage / fn.Transmission / fn.Sink constructors.
    """

    data: dict = {}

    # ── HEAT DEMAND ──────────────────────────────────────────────────────────
    # Absolute hourly demand in GWh/h (= GW equivalent for 1-h timestep)
    # Passed as operationRateFix to fn.Sink components

    data["Heat demand HTDHN, operationRateFix"] = _read_ts(
        "HeatDemand", "heatDemand_HTDHN_GWh.xlsx")

    data["Heat demand LTDHN, operationRateFix"] = _read_ts(
        "HeatDemand", "heatDemand_LTDHN_GWh.xlsx")

    data["Heat demand VLTDHN, operationRateFix"] = _read_ts(
        "HeatDemand", "heatDemand_VLTDHN_GWh.xlsx")

    # ── TEMPERATURE PROFILES ─────────────────────────────────────────────────
    # Units: Kelvin, shape (8760, 15)
    # Used by 02_Sustainability_Layer (not passed directly to FINE components)

    data["ERA5 ambient temperature, temperatureTimeSeries"] = _read_ts(
        "Temperature", "ERA5_ambientTemperature_K.xlsx")

    data["HTDHN network, supplyTemperature"] = _read_ts(
        "Temperature", "supplyTemperature_HTDHN_K.xlsx")

    data["HTDHN network, returnTemperature"] = _read_ts(
        "Temperature", "returnTemperature_HTDHN_K.xlsx")

    data["LTDHN network, supplyTemperature"] = _read_ts(
        "Temperature", "supplyTemperature_LTDHN_K.xlsx")

    data["LTDHN network, returnTemperature"] = _read_ts(
        "Temperature", "returnTemperature_LTDHN_K.xlsx")

    data["VLTDHN network, supplyTemperature"] = _read_ts(
        "Temperature", "supplyTemperature_VLTDHN_K.xlsx")

    data["VLTDHN network, returnTemperature"] = _read_ts(
        "Temperature", "returnTemperature_VLTDHN_K.xlsx")

    # ── HEAT SOURCES ─────────────────────────────────────────────────────────

    # Industrial waste heat
    data["Industrial waste heat, capacityMax"] = _read_scalar(
        "HeatSources", "industrialWasteHeatPotential_GWh.xlsx",
        col="industrialWasteHeat_GWh_per_year"
    ) / 8760 * 1.5    # convert annual GWh → peak GW (1.5× mean)

    data["Industrial waste heat, operationRateMax"] = _read_ts(
        "HeatSources", "industrialWasteHeatOperationRate.xlsx")

    # Geothermal
    data["Geothermal heat, capacityMax"] = _read_scalar(
        "HeatSources", "geothermalPotential_GWh.xlsx",
        col="geothermal_GWh_per_year"
    ) / 8760 * 1.2    # convert annual GWh → peak GW (1.2× mean, near-constant source)

    # Biomass boiler annual potential → max installed capacity proxy
    data["Biomass boiler, capacityMax"] = _read_scalar(
        "HeatSources", "biomassPotential_GWh.xlsx",
        col="biomass_GWh_per_year"
    ) / 8760 * 4.0    # convert annual GWh → max GW (assuming ~25% CF at peak)

    # Solar thermal capacity factor (dimensionless 0–1)
    data["Solar thermal, operationRateMax"] = _read_ts(
        "HeatSources", "solarThermalOperationRate.xlsx")

    # ── DH NETWORK ───────────────────────────────────────────────────────────

    data["DH pipes, eligibility"] = _read_mat(
        "DHNetwork", "DHPipeEligibility.xlsx")

    data["DH pipes, distances"] = _read_mat(
        "DHNetwork", "DHPipeDistance_km.xlsx")

    data["DH pipes, losses"] = _read_mat(
        "DHNetwork", "DHPipeLosses.xlsx")

    # ── COST AND TECHNOLOGY ASSUMPTIONS ──────────────────────────────────────
    # These are DataFrames with technology metadata, not passed directly to FINE.
    # buildModel.py reads specific cells from these tables.

    data["Heat technologies, costAssumptions"] = pd.read_excel(
        _BASE / "CostAssumptions" / "heatTechnologyCostAssumptions.xlsx",
        sheet_name="data", index_col=0, engine="openpyxl")

    data["Thermal storage, costAssumptions"] = pd.read_excel(
        _BASE / "CostAssumptions" / "thermalStorageCostAssumptions.xlsx",
        sheet_name="data", index_col=0, engine="openpyxl")

    data["DH pipes, costAssumptions"] = pd.read_excel(
        _BASE / "CostAssumptions" / "districtHeatingPipeCostAssumptions.xlsx",
        sheet_name="data", index_col=0, engine="openpyxl")

    return data


# ── Convenience: print data inventory ────────────────────────────────────────
def print_data_summary(data: dict) -> None:
    """Print a formatted summary of the data dict returned by getDHData()."""
    print(f"\n{'Key':<55} {'Type':<12} {'Shape'}")
    print("-" * 90)
    for key, val in data.items():
        t = type(val).__name__
        shape = str(val.shape) if hasattr(val, "shape") else "—"
        print(f"  {key:<53} {t:<12} {shape}")
    print(f"\n  Total keys: {len(data)}")


if __name__ == "__main__":
    data = getDHData()
    print_data_summary(data)
